### ISSUE TITLE
Manual label generation would be more useable.

### ISSUE THREAD

**Issue by algeboy** [MattthiasSchedel/bibtex-fetcher#2]
Bibtex manager (or perhaps the source of the search) generates its own bibtex label.  But these are often things a user needs to override with a label that is more memorable to use in an article, or at minimum we need to know whatever label gets generated.  I wonder if the default behavior of `Get Bibtex` should open a popup that you enter your desired label.  It might even preview what will be put in the bibtex as sometimes people edit these for bibliographic uniformity.

**Comment by MattthiasSchedel** [comment]
Hi, 
It is exam period right now so please excuse my late reply. 

I also think, a way to change the labels quickly would be useful. When i developed this plugin, i wanted to fetch bibtex with the least amount of clicks needed. Maybe we should add this as a setting for the user to choose if they want to change the labels after loading the bibtex. Maybe we could even implement a way to set up rules how a label should be constructed based on release date, author title etc. 

I will have time to work on the extension in early january and i have some other features planned like citing Books and websites. 

Greetings

**Comment by MattthiasSchedel** [comment]
I updated the extension. I hope this allows you to use your workflow. 

Greetings :)
