### ISSUE TITLE
Cannot find module './fetchBibTeX'

### ISSUE THREAD

**Issue by HadiSDev** [MattthiasSchedel/bibtex-fetcher#3]
I get this when loading the extension

```
2023-12-03 22:51:10.389 [error] Activating extension matthiasschedel.bibtex-manager failed due to an error:
2023-12-03 22:51:10.389 [error] Error: Cannot find module './fetchBibTeX'
```

**Comment by MattthiasSchedel** [comment]
Hey Hadi, How do you run VS code? Windows, Mac, Linux? VM etc. Give me some details.

**Comment by MattthiasSchedel** [comment]
I bundled the extension. This should fix your error. Can you please test if 3.6.1 works for you?

Greetings.

**Comment by Simon-Pokorny** [comment]
Works great! Thanks a lot! 
in the readme you mention a "Add Citation" button and in the screenshot I can see a section called Bibtex entries. Is that a feature that is not included in the latest version or can I configure it somewhere?

**Comment by MattthiasSchedel** [comment]
Hi, The "Add citation" button should still be there. 

The  "BibTex entries" section got removed indeed.

**Comment by Simon-Pokorny** [comment]
Okay thank you I found it :) 
I this this issue can be closed
